# Generated by Copilot
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=120, unique=False, blank=True, null=True),
        ),
    ]
