# Generated by Copilot
from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.all():
        base_slug = slugify(post.title)
        slug = base_slug
        n = 1
        while Post.objects.filter(slug=slug).exclude(pk=post.pk).exists():
            slug = f"{base_slug}-{n}"
            n += 1
        post.slug = slug
        post.save()

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
